import { collection, getDocs, addDoc, deleteDoc } from "firebase/firestore";
import { db } from "./firebase";
import type { University, ScholarshipProgram } from "./firestore";

export const SEED_UNIVERSITIES: University[] = [
  {
    nameAr: "جامعة الملك فهد للبترول والمعادن",
    nameEn: "King Fahd University of Petroleum and Minerals (KFUPM)",
    country: "المملكة العربية السعودية",
    city: "الظهران",
    type: "local",
    websiteUrl: "https://www.kfupm.edu.sa",
    admissionUrl: "https://www.kfupm.edu.sa/Admission",
    majors: ["الهندسة الميكانيكية", "الهندسة الكيميائية", "الهندسة المدنية", "الهندسة الكهربائية", "هندسة الحاسب", "علوم الحاسب", "هندسة البترول", "الهندسة الصناعية", "الرياضيات والإحصاء", "الفيزياء", "الكيمياء", "إدارة الأعمال", "المالية والاقتصاد", "الأمن السيبراني", "الذكاء الاصطناعي وعلوم البيانات"],
    languageRequirements: { ielts: "6.0", toefl: "79" },
    satRequired: "optional",
    actRequired: "optional",
    minHighSchoolGpa: 85,
    acceptanceRate: "يحتاج مراجعة",
    suitableForSaudiScholarship: false,
    weightedFormula: { highSchool: 30, qudorat: 30, tahsili: 40, note: "قد تتغير النسب حسب الكلية — يُنصح بمراجعة الموقع الرسمي" },
    admissionNotes: "جامعة حكومية متخصصة في التقنية والهندسة. أغلب البرامج باللغة الإنجليزية.",
    dataConfidence: "medium",
    needsReview: false,
    sourceLinks: ["https://www.kfupm.edu.sa"],
  },
  {
    nameAr: "جامعة الملك عبدالله للعلوم والتقنية",
    nameEn: "King Abdullah University of Science and Technology (KAUST)",
    country: "المملكة العربية السعودية",
    city: "ثول",
    type: "local",
    websiteUrl: "https://www.kaust.edu.sa",
    admissionUrl: "https://admissions.kaust.edu.sa",
    majors: ["علوم الحاسب", "الذكاء الاصطناعي وعلوم البيانات", "الهندسة الكهربائية", "الهندسة الكيميائية", "الأحياء والبيولوجيا", "الكيمياء", "علوم الأرض والجيولوجيا", "الطاقة المتجددة والاستدامة", "الرياضيات والإحصاء", "هندسة البترول"],
    languageRequirements: { ielts: "6.5", toefl: "79" },
    satRequired: "not_required",
    actRequired: "not_required",
    minHighSchoolGpa: 85,
    acceptanceRate: "يحتاج مراجعة",
    suitableForSaudiScholarship: false,
    weightedFormula: { note: "KAUST برامج دراسات عليا فقط (ماجستير/دكتوراه) — لا تنطبق الموزونة" },
    admissionNotes: "جامعة أبحاث متقدمة — تقبل الطلاب للدراسات العليا فقط. مُموّلة بالكامل مع رواتب للباحثين.",
    dataConfidence: "medium",
    needsReview: false,
    sourceLinks: ["https://www.kaust.edu.sa"],
  },
  {
    nameAr: "جامعة الملك عبدالعزيز",
    nameEn: "King Abdulaziz University (KAU)",
    country: "المملكة العربية السعودية",
    city: "جدة",
    type: "local",
    websiteUrl: "https://www.kau.edu.sa",
    admissionUrl: "https://admission.kau.edu.sa",
    majors: ["الطب", "طب الأسنان", "الصيدلة", "الهندسة الكهربائية", "الهندسة المدنية", "الهندسة الميكانيكية", "الهندسة الكيميائية", "علوم الحاسب", "إدارة الأعمال", "المالية والاقتصاد", "القانون والشريعة", "الأحياء والبيولوجيا", "الكيمياء", "اللغات والترجمة", "التربية والتعليم", "الإعلام والاتصال"],
    languageRequirements: {},
    satRequired: "not_required",
    actRequired: "not_required",
    minHighSchoolGpa: 80,
    acceptanceRate: "يحتاج مراجعة",
    suitableForSaudiScholarship: false,
    weightedFormula: { note: "تختلف النسب حسب الكلية — يحتاج مراجعة من الموقع الرسمي" },
    admissionNotes: "جامعة حكومية كبرى. القبول يعتمد على الموزونة التي تختلف بين الكليات.",
    dataConfidence: "low",
    needsReview: true,
    sourceLinks: ["https://www.kau.edu.sa"],
  },
  {
    nameAr: "جامعة الملك سعود",
    nameEn: "King Saud University (KSU)",
    country: "المملكة العربية السعودية",
    city: "الرياض",
    type: "local",
    websiteUrl: "https://www.ksu.edu.sa",
    admissionUrl: "https://admission.ksu.edu.sa",
    majors: ["الطب", "طب الأسنان", "الصيدلة", "الهندسة المدنية", "الهندسة الكهربائية", "الهندسة الميكانيكية", "علوم الحاسب", "الذكاء الاصطناعي وعلوم البيانات", "إدارة الأعمال", "المالية والاقتصاد", "القانون والشريعة", "التربية والتعليم", "الرياضيات والإحصاء", "الفيزياء", "الأحياء والبيولوجيا"],
    languageRequirements: {},
    satRequired: "not_required",
    actRequired: "not_required",
    minHighSchoolGpa: 80,
    acceptanceRate: "يحتاج مراجعة",
    suitableForSaudiScholarship: false,
    weightedFormula: { note: "تختلف النسب حسب الكلية — يحتاج مراجعة من الموقع الرسمي" },
    admissionNotes: "أقدم جامعة سعودية. برامج متنوعة وكليات طبية وهندسية مرموقة.",
    dataConfidence: "low",
    needsReview: true,
    sourceLinks: ["https://www.ksu.edu.sa"],
  },
  {
    nameAr: "جامعة الأمير سلطان",
    nameEn: "Prince Sultan University (PSU)",
    country: "المملكة العربية السعودية",
    city: "الرياض",
    type: "local",
    websiteUrl: "https://www.psu.edu.sa",
    admissionUrl: "https://www.psu.edu.sa/admission",
    majors: ["الهندسة الكهربائية", "هندسة الحاسب", "علوم الحاسب", "هندسة البرمجيات", "الأمن السيبراني", "إدارة الأعمال", "المالية والاقتصاد", "التسويق", "المحاسبة", "الإعلام والاتصال", "القانون والشريعة"],
    languageRequirements: { ielts: "5.0", toefl: "61" },
    satRequired: "not_required",
    actRequired: "not_required",
    minHighSchoolGpa: 75,
    acceptanceRate: "يحتاج مراجعة",
    suitableForSaudiScholarship: false,
    weightedFormula: { note: "جامعة خاصة — القبول يعتمد على المقابلة والاختبار الداخلي، يحتاج مراجعة" },
    admissionNotes: "جامعة خاصة في الرياض. تدريس باللغة الإنجليزية.",
    dataConfidence: "low",
    needsReview: true,
    sourceLinks: ["https://www.psu.edu.sa"],
  },
  {
    nameAr: "جامعة عفت",
    nameEn: "Effat University",
    country: "المملكة العربية السعودية",
    city: "جدة",
    type: "local",
    websiteUrl: "https://www.effatuniversity.edu.sa",
    admissionUrl: "https://www.effatuniversity.edu.sa/admission",
    majors: ["الهندسة الكهربائية", "هندسة الحاسب", "علوم الحاسب", "هندسة البرمجيات", "الذكاء الاصطناعي وعلوم البيانات", "إدارة الأعمال", "التسويق", "المحاسبة", "العمارة والتصميم", "الفنون والتصميم الجرافيكي"],
    languageRequirements: { ielts: "5.5", toefl: "72" },
    satRequired: "not_required",
    actRequired: "not_required",
    minHighSchoolGpa: 75,
    acceptanceRate: "يحتاج مراجعة",
    suitableForSaudiScholarship: false,
    weightedFormula: { note: "جامعة خاصة نسائية — القبول يعتمد على الاختبار الداخلي، يحتاج مراجعة" },
    admissionNotes: "جامعة نسائية خاصة في جدة. التدريس باللغة الإنجليزية.",
    dataConfidence: "low",
    needsReview: true,
    sourceLinks: ["https://www.effatuniversity.edu.sa"],
  },
  {
    nameAr: "جامعة الأمير محمد بن فهد",
    nameEn: "Prince Mohammad Bin Fahd University (PMU)",
    country: "المملكة العربية السعودية",
    city: "الخبر",
    type: "local",
    websiteUrl: "https://www.pmu.edu.sa",
    admissionUrl: "https://www.pmu.edu.sa/Admission",
    majors: ["الهندسة المدنية", "الهندسة الكهربائية", "هندسة الحاسب", "علوم الحاسب", "الهندسة الميكانيكية", "إدارة الأعمال", "المالية والاقتصاد", "الإعلام والاتصال", "الكيمياء", "الأحياء والبيولوجيا"],
    languageRequirements: { ielts: "5.5", toefl: "69" },
    satRequired: "not_required",
    actRequired: "not_required",
    minHighSchoolGpa: 75,
    acceptanceRate: "يحتاج مراجعة",
    suitableForSaudiScholarship: false,
    weightedFormula: { note: "جامعة خاصة — القبول يعتمد على المعدل وقد يشمل مقابلة، يحتاج مراجعة" },
    admissionNotes: "جامعة خاصة في الخبر. التدريس باللغة الإنجليزية.",
    dataConfidence: "low",
    needsReview: true,
    sourceLinks: ["https://www.pmu.edu.sa"],
  },
  {
    nameAr: "معهد ماساتشوستس للتكنولوجيا",
    nameEn: "Massachusetts Institute of Technology (MIT)",
    country: "الولايات المتحدة الأمريكية",
    city: "كامبريدج، ماساتشوستس",
    type: "international",
    websiteUrl: "https://www.mit.edu",
    admissionUrl: "https://mitadmissions.org",
    majors: ["الهندسة الميكانيكية", "هندسة الطيران والفضاء", "الهندسة الكهربائية", "هندسة الحاسب", "علوم الحاسب", "الذكاء الاصطناعي وعلوم البيانات", "الهندسة الكيميائية", "الرياضيات والإحصاء", "الفيزياء", "الكيمياء", "إدارة الأعمال", "المالية والاقتصاد", "الأمن السيبراني", "هندسة البترول"],
    languageRequirements: { toefl: "90", ielts: "7.0" },
    satRequired: "required",
    actRequired: "optional",
    minHighSchoolGpa: 95,
    acceptanceRate: "4%",
    suitableForSaudiScholarship: true,
    scholarshipPrograms: ["برنامج خادم الحرمين الشريفين"],
    weightedFormula: { note: "جامعة دولية — لا تنطبق الموزونة السعودية. القبول يعتمد على SAT والنشاط واللغة" },
    admissionNotes: "من أرقى الجامعات عالمياً. القبول تنافسي جداً (4%). تتطلب SAT وTOEFL/IELTS.",
    dataConfidence: "medium",
    needsReview: false,
    sourceLinks: ["https://mitadmissions.org"],
  },
  {
    nameAr: "جامعة ستانفورد",
    nameEn: "Stanford University",
    country: "الولايات المتحدة الأمريكية",
    city: "ستانفورد، كاليفورنيا",
    type: "international",
    websiteUrl: "https://www.stanford.edu",
    admissionUrl: "https://admission.stanford.edu",
    majors: ["الهندسة الكهربائية", "هندسة الحاسب", "علوم الحاسب", "الذكاء الاصطناعي وعلوم البيانات", "الطب", "القانون والشريعة", "إدارة الأعمال", "الأحياء والبيولوجيا", "الرياضيات والإحصاء", "الهندسة الميكانيكية", "هندسة الطيران والفضاء", "التسويق"],
    languageRequirements: { toefl: "100", ielts: "7.0" },
    satRequired: "optional",
    actRequired: "optional",
    minHighSchoolGpa: 95,
    acceptanceRate: "4%",
    suitableForSaudiScholarship: true,
    scholarshipPrograms: ["برنامج خادم الحرمين الشريفين"],
    weightedFormula: { note: "جامعة دولية — لا تنطبق الموزونة السعودية" },
    admissionNotes: "ثاني أعرق جامعات العالم. نسبة قبول 4%. SAT اختياري. TOEFL 100 أو IELTS 7.0.",
    dataConfidence: "medium",
    needsReview: false,
    sourceLinks: ["https://admission.stanford.edu"],
  },
  {
    nameAr: "جامعة هارفارد",
    nameEn: "Harvard University",
    country: "الولايات المتحدة الأمريكية",
    city: "كامبريدج، ماساتشوستس",
    type: "international",
    websiteUrl: "https://www.harvard.edu",
    admissionUrl: "https://college.harvard.edu/admissions",
    majors: ["القانون والشريعة", "الطب", "المالية والاقتصاد", "العلوم السياسية والعلاقات الدولية", "الفيزياء", "الكيمياء", "التاريخ والحضارة", "إدارة الأعمال", "علم النفس", "الأحياء والبيولوجيا", "الرياضيات والإحصاء"],
    languageRequirements: { toefl: "100", ielts: "7.0" },
    satRequired: "optional",
    actRequired: "optional",
    minHighSchoolGpa: 95,
    acceptanceRate: "3.5%",
    suitableForSaudiScholarship: true,
    scholarshipPrograms: ["برنامج خادم الحرمين الشريفين"],
    weightedFormula: { note: "جامعة دولية — لا تنطبق الموزونة السعودية" },
    admissionNotes: "أعرق جامعة في العالم. نسبة قبول 3.5%. SAT اختياري. دعم مالي كبير للطلاب الدوليين.",
    dataConfidence: "medium",
    needsReview: false,
    sourceLinks: ["https://college.harvard.edu/admissions"],
  },
  {
    nameAr: "جامعة أكسفورد",
    nameEn: "University of Oxford",
    country: "المملكة المتحدة",
    city: "أكسفورد",
    type: "international",
    websiteUrl: "https://www.ox.ac.uk",
    admissionUrl: "https://www.ox.ac.uk/admissions",
    majors: ["القانون والشريعة", "الطب", "الفلسفة والاقتصاد والسياسة", "الفيزياء", "الكيمياء", "علوم الحاسب", "الرياضيات والإحصاء", "الأحياء والبيولوجيا", "التاريخ والحضارة", "اللغات والترجمة", "المالية والاقتصاد"],
    languageRequirements: { ielts: "7.0", toefl: "110" },
    satRequired: "not_required",
    actRequired: "not_required",
    minHighSchoolGpa: 90,
    acceptanceRate: "17%",
    suitableForSaudiScholarship: true,
    scholarshipPrograms: ["برنامج خادم الحرمين الشريفين"],
    weightedFormula: { note: "جامعة دولية — لا تنطبق الموزونة السعودية. القبول يعتمد على A-Levels أو IB" },
    admissionNotes: "من أعرق الجامعات البريطانية. تتطلب IELTS 7.0. لا تعتمد SAT.",
    dataConfidence: "medium",
    needsReview: false,
    sourceLinks: ["https://www.ox.ac.uk/admissions"],
  },
  {
    nameAr: "جامعة كامبريدج",
    nameEn: "University of Cambridge",
    country: "المملكة المتحدة",
    city: "كامبريدج",
    type: "international",
    websiteUrl: "https://www.cam.ac.uk",
    admissionUrl: "https://www.undergraduate.study.cam.ac.uk/applying",
    majors: ["الرياضيات والإحصاء", "الطب", "الهندسة المدنية", "الهندسة الكيميائية", "علوم الحاسب", "المالية والاقتصاد", "القانون والشريعة", "الفيزياء", "الكيمياء", "الأحياء والبيولوجيا", "التاريخ والحضارة"],
    languageRequirements: { ielts: "7.5", toefl: "110" },
    satRequired: "not_required",
    actRequired: "not_required",
    minHighSchoolGpa: 90,
    acceptanceRate: "21%",
    suitableForSaudiScholarship: true,
    scholarshipPrograms: ["برنامج خادم الحرمين الشريفين"],
    weightedFormula: { note: "جامعة دولية — لا تنطبق الموزونة السعودية. تتطلب A-Levels أو ما يعادلها" },
    admissionNotes: "من أعرق الجامعات عالمياً. تتطلب IELTS 7.5. القبول تنافسي. لا تعتمد SAT.",
    dataConfidence: "medium",
    needsReview: false,
    sourceLinks: ["https://www.undergraduate.study.cam.ac.uk"],
  },
  {
    nameAr: "جامعة تورنتو",
    nameEn: "University of Toronto",
    country: "كندا",
    city: "تورنتو",
    type: "international",
    websiteUrl: "https://www.utoronto.ca",
    admissionUrl: "https://future.utoronto.ca/apply",
    majors: ["الهندسة المدنية", "الهندسة الكهربائية", "علوم الحاسب", "الذكاء الاصطناعي وعلوم البيانات", "الطب", "إدارة الأعمال", "المالية والاقتصاد", "الفنون والتصميم الجرافيكي", "القانون والشريعة", "التربية والتعليم", "الرياضيات والإحصاء", "الأحياء والبيولوجيا"],
    languageRequirements: { ielts: "6.5", toefl: "100", duolingo: "120" },
    satRequired: "optional",
    actRequired: "optional",
    minHighSchoolGpa: 85,
    acceptanceRate: "43%",
    suitableForSaudiScholarship: true,
    scholarshipPrograms: ["برنامج خادم الحرمين الشريفين"],
    weightedFormula: { note: "جامعة دولية — لا تنطبق الموزونة السعودية. القبول يعتمد على المعدل وإثبات اللغة" },
    admissionNotes: "من أفضل جامعات كندا. IELTS 6.5. كندا معتمدة في برنامج الابتعاث.",
    dataConfidence: "medium",
    needsReview: false,
    sourceLinks: ["https://future.utoronto.ca"],
  },
  {
    nameAr: "جامعة ملبورن",
    nameEn: "University of Melbourne",
    country: "أستراليا",
    city: "ملبورن",
    type: "international",
    websiteUrl: "https://www.unimelb.edu.au",
    admissionUrl: "https://study.unimelb.edu.au/how-to-apply",
    majors: ["الطب", "القانون والشريعة", "الهندسة الكهربائية", "الهندسة المدنية", "إدارة الأعمال", "علوم الحاسب", "الذكاء الاصطناعي وعلوم البيانات", "التربية والتعليم", "الأحياء والبيولوجيا", "العمارة والتصميم", "الطاقة المتجددة والاستدامة"],
    languageRequirements: { ielts: "6.5", toefl: "79" },
    satRequired: "not_required",
    actRequired: "not_required",
    minHighSchoolGpa: 80,
    acceptanceRate: "70%",
    suitableForSaudiScholarship: true,
    scholarshipPrograms: ["برنامج خادم الحرمين الشريفين"],
    weightedFormula: { note: "جامعة دولية — لا تنطبق الموزونة السعودية. القبول يعتمد على المعدل وإثبات اللغة" },
    admissionNotes: "من أفضل جامعات أستراليا. تتطلب IELTS 6.5. أستراليا معتمدة في برنامج الابتعاث.",
    dataConfidence: "medium",
    needsReview: false,
    sourceLinks: ["https://study.unimelb.edu.au"],
  },
];

export const SEED_SCHOLARSHIPS: ScholarshipProgram[] = [
  {
    nameAr: "برنامج خادم الحرمين الشريفين للابتعاث الخارجي",
    nameEn: "King Abdullah Scholarship Program (KASP)",
    provider: "هيئة الابتعاث والدراسات الخارجية — وزارة التعليم",
    description: "برنامج حكومي شامل يُتيح للمواطنين السعوديين المتميزين الدراسة في أرقى الجامعات حول العالم على نفقة الدولة. يشمل الرسوم الدراسية وتذاكر السفر وراتباً شهرياً. يتكون البرنامج من أربعة مسارات رئيسية تتناسب مع مستويات مختلفة.",
    requirements: [
      "مواطن سعودي",
      "معدل ثانوية لا يقل عن 85% — يحتاج مراجعة للشروط الدقيقة",
      "اجتياز اختبار لغة إنجليزية معتمد — يحتاج مراجعة للدرجة المطلوبة",
      "قبول من مؤسسة تعليمية معتمدة ضمن قائمة البرنامج",
    ],
    tracks: [
      {
        nameAr: "مسار الرواد",
        nameEn: "Al-Rowad Track",
        description: "مسار يهدف لابتعاث الطلاب إلى أفضل 30 جامعة/مؤسسة تعليمية عالمياً حسب قائمة البرنامج، ويدعم جميع التخصصات. يشترط الحصول على قبول غير مشروط من إحدى هذه المؤسسات.",
        requirements: ["القبول غير المشروط من إحدى أفضل 30 جامعة/مؤسسة تعليمية وفق قائمة البرنامج", "يدعم جميع التخصصات"],
        officialLink: "https://sites.moe.gov.sa/scholarship-program/paths/path-arruaad/",
        targetLevel: "بكالوريوس أو ماجستير",
        needsReview: false,
        notes: "المعلومات مستندة إلى الموقع الرسمي — يُنصح بمراجعة الرابط للتحقق من أحدث الشروط.",
      },
      {
        nameAr: "مسار إمداد",
        nameEn: "Imdad Track",
        description: "مسار يهدف لابتعاث الطلاب إلى أفضل 200 جامعة/مؤسسة تعليمية عالمياً في مجالات محددة ذات احتياج عالٍ في سوق العمل، لمرحلة البكالوريوس أو الماجستير.",
        requirements: ["القبول من ضمن أفضل 200 جامعة/مؤسسة تعليمية وفق قائمة البرنامج في هذا المسار", "مجالات محددة ذات أولوية في سوق العمل"],
        officialLink: "https://sites.moe.gov.sa/scholarship-program/paths/path-emdad/",
        targetLevel: "بكالوريوس أو ماجستير",
        needsReview: false,
        notes: "المعلومات مستندة إلى الموقع الرسمي — يُنصح بمراجعة الرابط للتحقق من التخصصات والشروط الحالية.",
      },
      {
        nameAr: "مسار واعد",
        nameEn: "Waed Track",
        description: "مسار للابتعاث المبتدئ بالتوظيف من خلال فرص تعلنها جهات وشركات مختلفة، وقد تختلف الدرجة العلمية والجامعة والمدة والشروط حسب كل فرصة. بعض الفرص تشمل بكالوريوس كعلوم الطيران، وبعضها ماجستير أو دبلوم أو تدريب.",
        requirements: ["تختلف الشروط حسب الجهة المُعلنة لكل فرصة — راجع الإعلان الخاص بكل فرصة"],
        officialLink: "https://sites.moe.gov.sa/scholarship-program/paths/path-waaid/",
        targetLevel: "يختلف حسب الفرصة",
        needsReview: true,
        notes: "⚠️ شروط مسار واعد تختلف بحسب الجهة والفرصة المعلنة — لا توجد شروط ثابتة موحدة لجميع فرصه.",
      },
      {
        nameAr: "مسار البحث والتطوير",
        nameEn: "Research & Development Track",
        description: "مسار مخصص للابتعاث في مجالات البحث والتطوير، ويشترط القبول لدرجة الدكتوراه من أفضل 200 جامعة/مؤسسة تعليمية حسب قائمة البرنامج.",
        requirements: ["القبول لدرجة الدكتوراه من ضمن أفضل 200 جامعة/مؤسسة تعليمية وفق قائمة البرنامج في هذا المسار", "التخصصات في مجالات البحث والتطوير ذات الأولوية"],
        officialLink: "https://sites.moe.gov.sa/scholarship-program/paths/path-albahthwaltatwir/",
        targetLevel: "دكتوراه",
        needsReview: false,
        notes: "⚠️ هذا المسار مخصص للدكتوراه فقط وليس مسار بكالوريوس عادي لطالب ثانوي — موجه للراغبين في الدراسات العليا البحثية.",
      },
    ],
    allowedCountries: ["الولايات المتحدة الأمريكية", "المملكة المتحدة", "كندا", "أستراليا", "ألمانيا", "فرنسا", "اليابان", "كوريا الجنوبية", "سنغافورة", "هولندا"],
    allowedMajors: ["الطب", "الهندسة", "علوم الحاسب", "العلوم", "إدارة الأعمال", "التربية", "القانون", "يحتاج مراجعة للقائمة الكاملة"],
    maxAge: "30 سنة للبكالوريوس — يحتاج مراجعة",
    minGpa: "85% — يحتاج مراجعة للشروط الدقيقة",
    languageRequirement: "IELTS 6.0 أو TOEFL iBT 79 — يحتاج مراجعة",
    approvedUniversities: ["MIT", "Stanford", "Harvard", "Oxford", "Cambridge", "جامعة تورنتو", "جامعة ملبورن", "يحتاج مراجعة للقائمة الكاملة"],
    officialUrl: "https://sites.moe.gov.sa/scholarship-program/",
    applicationUrl: "يحتاج مراجعة",
    requiresUniversityAdmission: true,
    requiresLanguageTest: true,
    requiresSAT: false,
    isActive: true,
    needsReview: false,
    lastVerifiedAt: "2025-01-01",
    notes: "⚠️ المعلومات للإرشاد فقط. تفاصيل البرنامج تتغير كل عام — يرجى دائماً مراجعة الموقع الرسمي لوزارة التعليم للشروط والمواعيد الحالية.",
  },
  {
    nameAr: "برنامج أرامكو للابتعاث الجامعي لخريجي الثانوية",
    nameEn: "Saudi Aramco College Degree Program (CDPNE)",
    provider: "أرامكو السعودية",
    description: "برنامج ابتعاث جامعي تقدمه أرامكو السعودية لخريجي وخريجات المرحلة الثانوية السعوديين للحصول على درجة البكالوريوس في تخصصات ضمن احتياج أرامكو. يغطي الرسوم الدراسية والمعيشة وتذاكر السفر، ويتضمن التزاماً بالعمل في أرامكو بعد التخرج.",
    requirements: [
      "مواطن سعودي خريج ثانوية",
      "معدل أكاديمي متميز — يحتاج مراجعة للشروط الدقيقة من أرامكو",
      "اجتياز SAT أو ACT — يحتاج مراجعة",
      "اجتياز اختبار لغة إنجليزية معتمد — يحتاج مراجعة",
    ],
    allowedCountries: ["الولايات المتحدة الأمريكية"],
    allowedMajors: ["الهندسة", "علوم الحاسب", "الكيمياء", "الجيولوجيا", "يحتاج مراجعة للقائمة الكاملة"],
    maxAge: "يحتاج مراجعة",
    minGpa: "يحتاج مراجعة",
    languageRequirement: "SAT أو ACT + TOEFL — يحتاج مراجعة",
    approvedUniversities: ["جامعات أمريكية معتمدة من أرامكو — يحتاج مراجعة"],
    officialUrl: "https://www.aramco.com/ar/careers/for-saudi-applicants/student-opportunities/college-degree-program",
    applicationUrl: "يحتاج مراجعة",
    requiresUniversityAdmission: true,
    requiresLanguageTest: true,
    requiresSAT: true,
    isActive: true,
    needsReview: false,
    notes: "⚠️ هذا برنامج ابتعاث جامعي لخريجي الثانوية للحصول على البكالوريوس — وليس برنامج تطوير مهني للموظفين. المعلومات التفصيلية تحتاج مراجعة من أرامكو السعودية مباشرة عبر الرابط الرسمي.",
  },
  {
    nameAr: "برنامج التدرج لخريجي المرحلة الثانوية - أرامكو",
    nameEn: "Saudi Aramco Apprenticeship Program",
    provider: "أرامكو السعودية",
    description: "برنامج تدرج وتدريب تقدمه أرامكو السعودية لخريجي المرحلة الثانوية لاكتساب المهارات اللازمة للوظائف التشغيلية والإدارية والكتابية وأعمال الصيانة. هذا برنامج تدريب داخلي وليس ابتعاثاً جامعياً خارجياً.",
    requirements: [
      "مواطن سعودي خريج ثانوية",
      "يحتاج مراجعة للشروط التفصيلية من أرامكو",
    ],
    allowedCountries: ["المملكة العربية السعودية"],
    allowedMajors: ["الوظائف التشغيلية", "الوظائف الإدارية", "أعمال الصيانة", "يحتاج مراجعة"],
    maxAge: "يحتاج مراجعة",
    minGpa: "يحتاج مراجعة",
    languageRequirement: "يحتاج مراجعة",
    approvedUniversities: [],
    officialUrl: "https://www.aramco.com/ar/careers/for-saudi-applicants/student-opportunities/apprenticeship-program",
    applicationUrl: "يحتاج مراجعة",
    requiresUniversityAdmission: false,
    requiresLanguageTest: false,
    requiresSAT: false,
    isActive: true,
    needsReview: false,
    notes: "⚠️ هذا برنامج تدرج/تدريب داخلي في أرامكو وليس ابتعاثاً جامعياً خارجياً — لا يتضمن الدراسة في جامعة خارج المملكة.",
  },
  {
    nameAr: "برنامج سابك للابتعاث والتطوير",
    nameEn: "SABIC Scholarship Program",
    provider: "سابك (SABIC)",
    description: "برنامج سابك لدعم موظفيها وأبناء موظفيها المتميزين للدراسة في جامعات مرموقة في التخصصات المرتبطة بنشاط الشركة.",
    requirements: [
      "مواطن سعودي",
      "ارتباط بمجال عمل سابك (هندسة كيميائية، بتروكيماويات، إدارة أعمال) — يحتاج مراجعة",
      "يحتاج مراجعة لجميع الشروط التفصيلية",
    ],
    allowedCountries: ["يحتاج مراجعة"],
    allowedMajors: ["الهندسة الكيميائية", "البتروكيماويات", "إدارة الأعمال", "يحتاج مراجعة"],
    maxAge: "يحتاج مراجعة",
    minGpa: "يحتاج مراجعة",
    languageRequirement: "يحتاج مراجعة",
    approvedUniversities: ["يحتاج مراجعة"],
    officialUrl: "https://www.sabic.com",
    applicationUrl: "يحتاج مراجعة",
    requiresUniversityAdmission: true,
    requiresLanguageTest: true,
    requiresSAT: false,
    isActive: true,
    notes: "⚠️ تفاصيل هذا البرنامج تحتاج مراجعة من المصدر الرسمي في سابك.",
  },
  {
    nameAr: "برنامج نيوم للابتعاث والمواهب",
    nameEn: "NEOM Scholarship & Talent Program",
    provider: "نيوم",
    description: "برنامج نيوم لدعم الكفاءات السعودية في المجالات المستقبلية كالتكنولوجيا والاستدامة والمدن الذكية والطاقة المتجددة.",
    requirements: [
      "مواطن سعودي",
      "التميز في المجالات التقنية والمستقبلية",
      "يحتاج مراجعة لجميع الشروط التفصيلية",
    ],
    allowedCountries: ["يحتاج مراجعة"],
    allowedMajors: ["التكنولوجيا", "الذكاء الاصطناعي", "الاستدامة", "الهندسة", "التصميم", "يحتاج مراجعة"],
    maxAge: "يحتاج مراجعة",
    minGpa: "يحتاج مراجعة",
    languageRequirement: "يحتاج مراجعة",
    approvedUniversities: ["يحتاج مراجعة"],
    officialUrl: "https://www.neom.com",
    applicationUrl: "يحتاج مراجعة",
    requiresUniversityAdmission: false,
    requiresLanguageTest: true,
    requiresSAT: false,
    isActive: true,
    needsReview: true,
    notes: "⚠️ برنامج جديد نسبياً — المعلومات تحتاج مراجعة من الموقع الرسمي.",
  },
  {
    nameAr: "برامج وزارة التعليم للابتعاث والمنح",
    nameEn: "Ministry of Education Scholarship Programs",
    provider: "وزارة التعليم — المملكة العربية السعودية",
    description: "تُطلق وزارة التعليم برامج ابتعاث متنوعة بشكل دوري إلى جانب برنامج خادم الحرمين، منها منح ثنائية مع دول محددة، وبرامج للدراسات العليا، ومنح التميز في التخصصات الصحية والتقنية.",
    requirements: [
      "مواطن سعودي",
      "يحتاج مراجعة للشروط التفصيلية لكل برنامج",
    ],
    allowedCountries: ["يحتاج مراجعة — تختلف حسب كل برنامج"],
    allowedMajors: ["يحتاج مراجعة — تختلف حسب كل برنامج"],
    maxAge: "يحتاج مراجعة",
    minGpa: "يحتاج مراجعة",
    languageRequirement: "يحتاج مراجعة",
    approvedUniversities: ["يحتاج مراجعة"],
    officialUrl: "https://www.moe.gov.sa",
    applicationUrl: "يحتاج مراجعة",
    requiresUniversityAdmission: true,
    requiresLanguageTest: true,
    requiresSAT: false,
    isActive: true,
    needsReview: true,
    notes: "⚠️ راجع الموقع الرسمي لوزارة التعليم للاطلاع على أحدث البرامج والمواعيد — https://www.moe.gov.sa",
  },
];

export const seedIfEmpty = async () => {
  try {
    const uniSnap = await getDocs(collection(db, "universities"));
    if (uniSnap.docs.length < 8) {
      const existingNames = new Set(uniSnap.docs.map((d) => (d.data() as any).nameEn?.split(" (")[0] ?? ""));
      const toAdd = SEED_UNIVERSITIES.filter((u) => !existingNames.has(u.nameEn.split(" (")[0]));
      await Promise.all(toAdd.map((u) => addDoc(collection(db, "universities"), u)));
    }
    const schSnap = await getDocs(collection(db, "scholarship_programs"));
    if (schSnap.docs.length === 0) {
      await Promise.all(SEED_SCHOLARSHIPS.map((s) => addDoc(collection(db, "scholarship_programs"), s)));
    }
  } catch (err) {
    console.error("Seed error:", err);
  }
};

export const reseedScholarshipsOnly = async () => {
  const schSnap = await getDocs(collection(db, "scholarship_programs"));
  await Promise.all(schSnap.docs.map((d) => deleteDoc(d.ref)));
  await Promise.all(SEED_SCHOLARSHIPS.map((s) => addDoc(collection(db, "scholarship_programs"), s)));
};

export const forceReseedAll = async () => {
  const [uniSnap, schSnap] = await Promise.all([
    getDocs(collection(db, "universities")),
    getDocs(collection(db, "scholarship_programs")),
  ]);
  await Promise.all([
    ...uniSnap.docs.map((d) => deleteDoc(d.ref)),
    ...schSnap.docs.map((d) => deleteDoc(d.ref)),
  ]);
  await Promise.all([
    ...SEED_UNIVERSITIES.map((u) => addDoc(collection(db, "universities"), u)),
    ...SEED_SCHOLARSHIPS.map((s) => addDoc(collection(db, "scholarship_programs"), s)),
  ]);
};
